openapi: 3.0.3
info:
  title: Simple Hello API
  version: 1.0.0
  description: A minimal OpenAPI spec with one GET endpoint.

servers:
  - url: http://localhost:3000
    description: Local development server

paths:
  /hello:
    get:
      summary: Returns a greeting message
      operationId: getHello
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Greeting'

components:
  schemas:
    Greeting:
      type: object
      properties:
        message:
          type: string
          example: Hello, world!
